name: Hobbyzone CICD with Gradle

on:
  push:
    branches: [ "develop" ]

jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./hobbyzone/gradlew

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-


      - name: Run tests and generate Jacoco report
        continue-on-error: true
        run: |
          cd hobbyzone
          ./gradlew jacocoTestReport

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: hobbyzone/build/reports/tests/test/

      - name: Check coverage and fail if below threshold
        if: ${{ steps.jacoco.outputs.coverage < '50.0' }}
        run: |
          echo "JaCoCo overall coverage is below threshold. Current coverage: ${{ steps.jacoco.outputs.coverage }}"
          exit 1

      - name: Copy jar file to remote VM
        if: success()
        uses: appleboy/scp-action@master
        with:
          host: 35.216.7.103
          key: ${{ secrets.HOBBYZONE_BE_SERVER_SSH_KEY }}
          username: rsa-key-20240701
          password:
          port: 22
          source: "hobbyzone/build/libs/*.jar"
          target: "/home/rsa-key-20240701"
          strip_components: 3

      - name: Deploy new version in VM
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: 35.216.7.103
          key: ${{ secrets.HOBBYZONE_BE_SERVER_SSH_KEY }}
          username: rsa-key-20240701
          script: sudo bash /home/rsa-key-20240701/deploy-new-version.sh