name: Hobbyzone CICD with Gradle

on:
  push:
    branches: [ "develop" ]

jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./hobbyzone/gradlew

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: "build/reports/jacoco/test/jacocoTestReport.xml"
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 50
          min-coverage-changed-files: 50

      - name: Build with Gradle
        run: ./hobbyzone/gradlew clean build --exclude-task test

      - name: Copy jar file to remote VM
        uses: appleboy/scp-action@master
        with:
          host: 35.216.7.103
          key: ${{ secrets.HOBBYZONE_BE_SERVER_SSH_KEY }}
          username: rsa-key-20240701
          port: 22
          source: "build/libs/*.jar"
          target: "/home/rsa-key-20240701/app"
          strip_components: 2

      - name: Deploy new version in VM
        uses: appleboy/ssh-action@master
        with:
          host: 35.216.7.103
          key: ${{ secrets.HOBBYZONE_BE_SERVER_SSH_KEY }}
          username: rsa-key-20240701
          script: sudo bash /home/rsa-key-20240701/app/deploy-new-version.sh